### PR TITLE
Added a public method setRecording to OfMeetPlugin

### PR DESCRIPTION
**Pull request by deleolajide**
Added a public method called by inflection from another plugin to record JVB conferences.
The old public method setRecording on conference is replaced by setRecording on Conference contents. In other words, setRecording is done explicitly for "audio" and "video" content types.

### CODE REVIEW

**Comment by guusdk** [comment]
Ugh, the change is hiding in a lot of white-space changes. Could you reformat the commit, please?

Also: I was under the impression that Jitsi (upstream) no longer supports recordings (other than to things like Youtube). What functionality are you referring to in this PR exactly?

**Comment by deleolajide** [comment]
>Ugh, the change is hiding in a lot of white-space changes. Could you reformat the commit, please?

Not sure what to do? I really can't afford to change text editors right now. As you advised, I changed my editor to use white spaces instead of tabs.

**Comment by deleolajide** [comment]
>Also: I was under the impression that Jitsi (upstream) no longer supports recordings (other than to things like Youtube). What functionality are you referring to in this PR exactly?

libjitsi supports media recording of all channels independently. 
jitsi-videobridge changed its public methods and broke ofmeet. 
jitsi-meet has opted to use a user agent (jibri) to obtain a single stream of mixed audio and active speaker video for simpler recording and broadcasting via you-tube

**Comment by guusdk** [comment]
Note to self: adding ?w=1 to a github diff url will hide all whitespace-only changes! :)

**Pull request merged**
