### PR TITLE
This PR does the following:

### PR DESCRIPTION
**Pull request by deleolajide**
1. fix the change in meeting URLs from version 0.3.x to 0.9.x
2. finishing the Quartz CRON job triggers for meetings.
3. add support for notifications via IM as used by Pade
4. fix various bugs, add missing files/folders

image

### CODE REVIEW

**Comment by guusdk** [comment]
Should these changes be mentioned in the changelog?

**Comment by deleolajide** [comment]
>Should these changes be mentioned in the changelog?

Yes, they should :-) Can you please do me a favour and paste the 4 items listed above when you update the changelog file.

**Comment by guusdk** [comment]
No problem. Do you want to include them as-is? The latter is somewhat... generic. :) Do you want references to issues that are logged somewhere?

**Comment by deleolajide** [comment]
>Do you want references to issues that are logged somewhere?

So true. Item 4 is to generic. I did not log all the minor issues I fixed as I proceeded. Some were old and some were introduced in the transition from 0.3.x to 0.9.x. Lets drop item 4.

**Pull request merged**
